using DG.Tweening;
using UnityEngine;

public class BulletManager : MonoBehaviour
{
    [Header("Parameter")]
    [SerializeField] private float damageValue;
    [SerializeField] private float lifeTime;
    private float lifeTimer;
    [SerializeField] private float moveSpeed;
    private Vector3 moveVector;
    private float adjustDistance;

    [Header("Effects")]
    [SerializeField] private ParticleSystem bulletParticle;
    [SerializeField] private GameObject hitPrefab;

    [Header("Rotation")]
    [SerializeField] private float rotateSpeed;

    // OtherObjects
    private Transform bossCoreTransform;
    private BossCoreManager bossCoreManager;

    public void Initialize(Transform _bossCoreTransform, Vector3 _moveVector, float _adjustDistance)
    {
        // ‰ñ“]‚·‚é
        transform.DORotate(Vector3.right * 360f, 0.4f, RotateMode.WorldAxisAdd).SetLoops(-1, LoopType.Restart);

        // BossCore‚ğæ“¾
        bossCoreTransform = _bossCoreTransform;
        bossCoreManager = bossCoreTransform.GetComponent<BossCoreManager>();

        // ˆÚ“®•ûŒü‚ğæ“¾
        moveVector = Vector3.Normalize(_moveVector);

        // ‚¸‚ç‚·‹——£‚ğæ“¾
        adjustDistance = _adjustDistance;

        // ¶‘¶ŠÔ‚Ìİ’è
        lifeTimer = lifeTime;
    }

    void Update()
    {
        lifeTimer -= Time.deltaTime;
        if (lifeTimer < 0) { DestroySelf(); }

        // ˆÚ“®
        transform.position += moveVector * (moveSpeed * Time.deltaTime);

        // ‰ñ“]
        transform.Rotate(new());

        // Pillar‚ÉUŒ‚
        foreach (GameObject pillar in GameObject.FindGameObjectsWithTag("Pillar"))
        {
            Vector3 pillarRePosition = pillar.transform.position;

            if (IsHitObject(ref pillarRePosition))
            {
                Vector3 diffVector = -moveVector * adjustDistance;

                // HitEffectì¬
                Instantiate(hitPrefab, pillarRePosition + diffVector, Quaternion.identity);

                // Á–Å‚·‚é
                DestroySelf();
            }
        }

        // BossCore‚ÉUŒ‚
        Vector3 bossCoreRePosition = bossCoreTransform.position;

        if (IsHitObject(ref bossCoreRePosition))
        {
            Vector3 toPlayer = Vector3.Normalize(transform.position - bossCoreRePosition);
            Vector3 diffVector = toPlayer * adjustDistance;

            // HitEffectì¬
            Instantiate(hitPrefab, bossCoreRePosition + diffVector, Quaternion.identity);

            // Damage‚ğ—^‚¦‚é
            bossCoreManager.Damage(damageValue);

            // Á–Å‚·‚é
            DestroySelf();
        }
    }

    void DestroySelf()
    {
        // Effect‚ÌeqŠÖŒW‚ğ‰ğœ‚·‚é
        bulletParticle.transform.parent = null;

        // ParticleSystem‚Ì’â~
        bulletParticle.Stop();

        // DOTween‚Ì’â~
        DOTween.Kill(gameObject);

        // Á–Å
        Destroy(gameObject);
    }
    bool IsHitObject(ref Vector3 _objectPosition)
    {
        // ‚‚³‚ğPlayer‚É‡‚í‚¹‚½VÀ•W
        _objectPosition = new(_objectPosition.x, transform.position.y, _objectPosition.z);

        // ‹——£‚ğæ“¾
        float distance = Vector3.Distance(transform.position, _objectPosition);

        // ˆê’è‹——£“à‚ÌƒIƒuƒWƒFƒNƒg‚ğUŒ‚‚·‚é
        if (distance < 0.5f)
        {
            return true;
        }
        return false;
    }
}
